language: generic 

sudo: required

services:
  - docker

before_install:
  - docker build -t stephanyu/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stephanyu/docker-react yarn run test